name = "CFCoordinateReferenceSystems"
uuid = "fed75b75-709c-453e-a27b-7a1357b6667b"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>", "Anshul Singhvi <anshulsinghvi@gmail.com>", "and contributors"]
version = "0.1.0"

[deps]
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
GeoFormatTypes = "0.4"
JSON3 = "1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
