name = "CFCoordinateReferenceSystems"
uuid = "fed75b75-709c-453e-a27b-7a1357b6667b"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>", "Anshul Singhvi <anshulsinghvi@gmail.com>", "and contributors"]
version = "0.1.0"

[deps]
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[weakdeps]
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"

[extensions]
CFCoordinateReferenceSystemsProjExt = "Proj"

[compat]
Aqua = "0.8"
ArchGDAL = "0.9, 0.10"
GeoFormatTypes = "0.4"
JET = "0.9"
JSON3 = "1"
OrderedCollections = "1.8"
Proj = "1.8"
SafeTestsets = "0.1"
Test = "1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ArchGDAL", "JET", "SafeTestsets", "Test"]
